version: '3.1'

services:

  db:
    image: postgres:alpine
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-db
